# Change these first
owner: allenstechio # Your GitHub organization or username, where this repository lives
repo: homelab-status # The name of this repository

sites:
  - name: Allenstech.io
    url: https://allenstech.io
  - name: Seer
    url: https://request.allenstech.io

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /homelab-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Allenstech Homelab Status
  introTitle: "**Allenstechio** status page, powered entirely by GitHub."
  introMessage: This is a status page for Allenstech homelab services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
